theme: jekyll-theme-minimal
title: Welcome to Skylar's homepage!
description: I am a web developer with my primary experience being in Java development. Interests include learning new programming languages, design and architecture. I've written about computer security, Git version control, and have some of my project work linked here.
collections:
  projects:
    output: true
  git:
    output: true
  security:
    output: true
  agile:
    output: true
  java:
    output: true
sidebar:
  - label: Projects
    children:
      - git
      - security
exclude:
  - Gemfile
  - Gemfile.lock
